server:
  port: 8080
javax:
  sql:
    DataSource:
      default:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dataSource:
          url: jdbc:h2:mem:app
          user: sa
          password: ""
