name: Build
on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: java
    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >
        mvn -B -ntp verify
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
